const MOCK_CHAIN_ID = 1337;
const MOCK_JSON_RPC_SERVER_PORT = 8545;
const MOCK_PROVIDER_RPC_CONFIG = {
  [MOCK_CHAIN_ID]: `http://localhost:${MOCK_JSON_RPC_SERVER_PORT}`,
};

export { MOCK_CHAIN_ID, MOCK_JSON_RPC_SERVER_PORT, MOCK_PROVIDER_RPC_CONFIG };
